version: '3.7'
services:

  mysql:
    environment:
      MYSQL_DATABASE: "partkeepr"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    restart: always
    volumes:
       - pk-db:/var/lib/mysql

  partkeepr:
    build:
      context: ./partkeepr
    ports:
      - "${APP_PORT}:80"
    restart: always
    volumes:
      - "pk-dir:/var/www/partkeepr"

volumes:
  pk-db:
  pk-dir: