version: '3.7'
services:

  mysql:
    environment:
      MYSQL_DATABASE: "partkeepr"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    restart: always
    volumes:
       - pk-db:/var/lib/mysql
    networks:
       - net
      
  app:
    build:
      context: ./app
    ports:
      - "${APP_PORT}:80"
    restart: always
    volumes:
      - "./PartKeepr:/var/www/partkeepr"
    networks:
      - net

  composer:
    build:
      context: ./composer
    volumes:
      - "./PartKeepr:/home/application"

  vscode:
    image: codercom/code-server
    ports:
      - "8081:8080"
    environment:
      - PASSWORD=pass
    volumes:
      - "./PartKeepr:/home/coder/workspace"


volumes:
  pk-db:

networks:
    net:
        driver: bridge
